// Generated by native/product-core/scripts/generate-bindings.mjs. Do not edit.
package com.tex8.monero.productcore

object MfwAppVaultContract {
    const val STATE_SCHEMA_VERSION: Int = 1
    const val STATE_SCHEMA_SHA256: String = "7e2049872d2060476ebebd5a9fab9f4e3a39a5df4e07d0cde482df6b57bd6356"
    const val DEFAULT_AUTO_LOCK_SECONDS: Long = 1800L
    val AUTO_LOCK_SECONDS: Set<Long> = setOf(0L, 60L, 300L, 900L, 1800L, 3600L)
    val UNLOCK_BACKOFF_SECONDS: LongArray = longArrayOf(0L, 2L, 5L, 30L, 60L, 120L, 240L, 300L)
    const val PASSWORD_MINIMUM_CHARACTERS: Int = 12
    const val PASSWORD_MAXIMUM_CHARACTERS: Int = 1024
    const val PASSWORD_KDF_VERSION: Int = 19
    const val PASSWORD_KDF_MEMORY_KIB: Int = 65536
    const val PASSWORD_KDF_ITERATIONS: Int = 3
    const val PASSWORD_KDF_PARALLELISM: Int = 1
    const val PASSWORD_KDF_SALT_BYTES: Int = 16
    const val PASSWORD_KDF_DIGEST_BYTES: Int = 32
    const val WARMUP_MAXIMUM_CONCURRENT_WALLETS: Int = 4
    const val PROTECTION_MODE_UNCONFIGURED: Int = 0
    const val PROTECTION_MODE_PASSWORD: Int = 1
    const val PROTECTION_MODE_SYSTEM: Int = 2
    const val PROTECTION_MODE_NONE: Int = 3
    const val PRESENTATION_PREPARING: Int = 0
    const val PRESENTATION_WELCOME: Int = 1
    const val PRESENTATION_PROTECTION_SETUP: Int = 2
    const val PRESENTATION_UNLOCK_PASSWORD: Int = 3
    const val PRESENTATION_UNLOCK_SYSTEM: Int = 4
    const val PRESENTATION_CONTENT: Int = 5
    const val PRESENTATION_BACKOFF: Int = 6
    const val MIGRATION_LEGACY_AUTHORITATIVE: Int = 0
    const val MIGRATION_STAGED: Int = 1
    const val MIGRATION_ACTIVATED: Int = 2
    const val MIGRATION_VERIFIED: Int = 3
    const val MIGRATION_COMMITTED: Int = 4
    const val MIGRATION_CLEANUP_COMPLETE: Int = 5
    const val EVENT_WELCOME_CONTINUE: Int = 1
    const val EVENT_CONFIGURE_PASSWORD_SUCCESS: Int = 2
    const val EVENT_CONFIGURE_SYSTEM_SUCCESS: Int = 3
    const val EVENT_UNLOCK_SUCCESS: Int = 4
    const val EVENT_UNLOCK_FAILURE: Int = 5
    const val EVENT_USER_ACTIVITY: Int = 6
    const val EVENT_TIMEOUT: Int = 7
    const val EVENT_MANUAL_LOCK: Int = 8
    const val EVENT_CHANGE_TO_PASSWORD: Int = 9
    const val EVENT_CHANGE_TO_SYSTEM: Int = 10
    const val EVENT_MIGRATION_ADVANCE: Int = 11
    const val EVENT_SKIP_PROTECTION: Int = 12
    const val STEP_UP_SEED_EXPORT: Int = 1
    const val STEP_UP_PRIVATE_KEY_EXPORT: Int = 2
    const val STEP_UP_SEND_COMMIT: Int = 3
    const val STEP_UP_PROTECTION_CHANGE: Int = 4
    const val STEP_UP_LOCAL_RESET: Int = 5
    const val STEP_UP_HOSTED_DATA_DELETE: Int = 6
    fun unlockDelaySeconds(failures: Int): Long {
        if (failures <= 0) return 0L
        return UNLOCK_BACKOFF_SECONDS[minOf(failures, UNLOCK_BACKOFF_SECONDS.lastIndex)]
    }
}
