export const repositoryUrl = "https://github.com/tex8com/monero-fast-wallet";
export const releaseUrl = `${repositoryUrl}/releases`;
import { generatedWebsiteCopy, localeMetadata } from "./locales.generated.js";

const shared = {
  brand: "Monero Fast Wallet",
  github: "GitHub",
  de: "DE",
  en: "EN",
  source: "Quellcode",
};

export const copy = {
  de: {
    ...shared,
    lang: "de",
    switchLabel: "English version",
    menu: "Menü öffnen",
    close: "Menü schließen",
    download: "Download",
    nav: [
      ["#wallet", "Wallet"],
      ["#features", "Funktionen"],
      ["#enthusiast", "Monero Enthusiast"],
      ["#benchmarks", "Benchmark"],
      ["#mfn", "MFN"],
      ["#open-source", "Open Source"],
    ],
    heroSlides: [
      {
        eyebrow: "Monero für jeden",
        title: ["Privates Geld.", "Endlich einfach."],
        body: "Eine verständliche Monero-Wallet für Smartphone und Desktop. Deine Schlüssel bleiben deine – vom ersten Empfang bis zur letzten Bestätigung.",
        primary: "Apps entdecken",
        secondary: "So funktioniert es",
      },
      {
        eyebrow: "Mobile + Desktop",
        title: ["Ein Ablauf.", "Fünf Plattformen."],
        body: "React Native auf iOS und Android, Tauri 2 auf macOS, Windows und Linux. Andere Hardware, dieselbe einfache Bedienung.",
        primary: "Zu den Downloads",
        secondary: "Funktionen ansehen",
      },
      {
        eyebrow: "Monero Fast Node",
        title: ["Schneller synchronisieren.", "Monero bleibt Monero."],
        body: "Monero Fast Node beschleunigt den Datenweg. Adressen, Transaktionen und Konsens bleiben vollständig Monero-kompatibel.",
        primary: "MFN verstehen",
        secondary: "Messwerte prüfen",
      },
    ],
    heroCarouselLabel: "Neuigkeiten und Highlights",
    previousSlide: "Vorheriger Inhalt",
    nextSlide: "Nächster Inhalt",
    slideLabel: "Inhalt",
    trust: ["Selbstverwahrt", "Open Source", "Nativer Monero-Core"],
    preview: "Platzhalter – echte App-Screenshots folgen",
    simpleEyebrow: "Einfach statt technisch",
    simpleTitle: "Gebaut für den Alltag, nicht nur für Experten.",
    simpleBody: "Die komplizierten Dinge erledigt die App. Du siehst nur das, was du für die nächste sichere Entscheidung brauchst.",
    features: [
      ["Senden in zwei Schritten", "Adresse scannen oder einfügen, dann Betrag wählen und vor dem Senden klar prüfen."],
      ["Einfach empfangen", "Großer QR-Code, kopierbare Adresse, Subadressen und die neuesten Zahlungen an einem Ort."],
      ["Ehrlicher Sync-Status", "Echte Phase, Blockhöhen und Restblöcke. Eine Restzeit erscheint nur, wenn sie belastbar ist."],
      ["Ein Schutz für die ganze App", "Biometrie oder Betriebssystemschutz öffnet alle gespeicherten Wallets gemeinsam."],
      ["Ledger bleibt Ledger", "Der Spend Key verlässt das Gerät nie; Transaktionen brauchen deine Bestätigung am Ledger."],
      ["Privacy oder Privacy + Komfort", "Du entscheidest, ob zusätzlich eine klar markierte Fast Wallet erstellt wird."],
    ],
    modeEyebrow: "Eine klare Wahl",
    modeTitle: "Die Fast Wallet ist ein Zusatz, kein Ersatz.",
    modeBody: "Deine normalen Wallets bleiben lokal. Mit Privacy + Komfort kommt eine separate Empfangs-Wallet für schnelle Hinweise dazu.",
    privacy: "Privacy",
    privacyText: "Lokale Monero-Wallets ohne gehostete Fast Wallet.",
    comfort: "Privacy + Komfort",
    comfortText: "Derselbe private Core plus separate Fast Wallet für schnellere Empfangshinweise.",
    modePoints: ["Kein Seed und kein Spend Key werden übertragen.", "Die Fast Wallet ist überall eindeutig markiert.", "Der Modus kann später in den Einstellungen geändert werden.", "Die Open-Source-Dienste können auf eigener Infrastruktur laufen."],
    enthusiastEyebrow: "Monero Enthusiast · optionale Community",
    enthusiastTitle: "Menschen, Ideen und Services finden – getrennt von deiner Wallet.",
    enthusiastBody: "Monero Enthusiast ist ein eigener Community-Bereich in der App. Deine pseudonyme Community-Identität wird nicht mit Wallet-Adresse, Guthaben, Verlauf, Seed oder Schlüsseln verknüpft.",
    enthusiastPoints: [
      ["Lokal suchen", "Ein signierter öffentlicher Katalog wird auf das Gerät geladen. Suche und persönliche Sortierung laufen lokal statt als Profil auf dem Server."],
      ["Nur nach Zustimmung verbinden", "Ein persönlicher Kontakt entsteht erst, wenn die empfangende Person eine Profil-zu-Profil-Anfrage annimmt."],
      ["Privat schreiben", "Akzeptierte Kontakte können in einem separaten Ende-zu-Ende-verschlüsselten Matrix-Chat miteinander sprechen."],
      ["Kontrolle behalten", "Listings laufen ab, können gelöscht und gemeldet werden. Die Community bleibt ein eigener, optionaler Bereich."],
    ],
    enthusiastPreviewLabel: "Lokale Community-Suche",
    enthusiastPreviewPlaceholder: "Node, Meetup oder Service suchen …",
    enthusiastPreviewResults: [
      ["MENSCH", "Panama Monero Meetup", "Community · ungefährer Bereich optional"],
      ["IDEE", "Eigener Monero Node", "Open Source · Einsteigerfreundlich"],
      ["SERVICE", "Monero vor Ort verstehen", "Öffentliches Listing · 18 Tage"],
    ],
    enthusiastPrivacyLabel: "Wallet getrennt",
    enthusiastPrivacyText: "Keine Wallet-Adresse, kein Guthaben, kein Verlauf und keine Schlüssel im Community-Profil.",
    enthusiastStatus: "Im Quellcode umgesetzt · öffentliche Freigabe noch in Prüfung",
    enthusiastDownload: "App herunterladen",
    enthusiastPrivacyLink: "Privacy-Modell ansehen",
    benchmarkEyebrow: "Gemessen, nicht behauptet",
    benchmarkTitle: "Derselbe Blockbereich. Ein schnellerer Datenweg.",
    benchmarkBody: "Alle drei aktuellen Core-Läufe scannten dieselben 161.523 Mainnet-Blöcke seriell bis zum gleichen eingefrorenen Zielblock.",
    benchmarkRows: [
      ["Original Monero Wallet", "215 Blöcke/s · 12 min 31 s", "8%"],
      ["Monero Fast Wallet", "752 Blöcke/s · 3 min 35 s", "27%"],
      ["Fast Wallet + ScanPack", "2.802 Blöcke/s · 58 s", "100%"],
    ],
    faster: "schneller in diesem Test",
    benchmarkPending: "Validierter aktueller Core · 13. August 2026",
    important: "Wichtig",
    benchmarkNote: "Ein kontrollierter Vergleich – keine Geschwindigkeitsgarantie für jedes Gerät oder Netzwerk. Der gemessene ScanPack-Servercache belegte 34,351 GiB.",
    method: "Methode und Rohdaten",
    derivationEyebrow: "Beschleunigung im Wallet-Core",
    derivationTitle: "Die Kryptografie nutzt die passende Hardware.",
    derivationBody: "Der Wallet-Core wählt je nach Gerät einen verifizierten CPU-, Metal- oder CUDA-Pfad. Kleine Aufgaben bleiben bewusst auf der CPU; bei einem Fehler wird sicher auf die CPU zurückgeschaltet.",
    derivationUnit: "Derivationen pro Sekunde",
    derivationRows: [
      { kind: "baseline", platform: "REFERENZ", status: "1 Thread", title: "Original Monero Ref10", rate: "27.030,166", comparison: "1,00× · archivierter Basiswert" },
      { kind: "mobile", platform: "ARM64 MEHRKERN", status: "NEON-fähig", title: "Pixel 8 Pro · 9 Worker", rate: "77.962,845", comparison: "7,83× gegenüber Ref10 auf demselben Gerät" },
      { kind: "metal", platform: "APPLE METAL", status: "Produktpfad", title: "Apple M4 · Metal M17", rate: "459.493,923", comparison: "17,00× normalisiert" },
      { kind: "cuda", platform: "NVIDIA CUDA", status: "Formaler Median", title: "RTX 5090 · CUDA C7", rate: "26.818.054,526", comparison: "992,15× normalisiert" },
    ],
    derivationNote: "Derivationen/s messen D = 8 × a × R im kryptografischen Kernel – nicht Blöcke/s und nicht die gesamte Sync-Zeit. Mobile verwendet aktuell den optimierten ARM64-Mehrkernpfad auf NEON-fähiger Hardware; ein separater NEON-Kernel wird nicht behauptet. CUDA ist optional für passende Windows-/Linux-Pakete; Metal ist der verifizierte macOS-Pfad.",
    derivationMethod: "Beschleunigung, Methodik und Rohdaten",
    downloadEyebrow: "Eine Wallet, jeder Bildschirm",
    downloadTitle: "Lade das passende Paket für dein Gerät.",
    downloadBody: "Die Plattformen bleiben sichtbar. Download-Links werden erst nach der öffentlichen Freigabe aktiviert.",
    coming: "Release-Bereich",
    packages: { apk: "APK herunterladen", dmg: "DMG herunterladen", exe: "EXE herunterladen", rpm: "RPM herunterladen", deb: "DEB herunterladen", appimage: "AppImage herunterladen" },
    releaseGate: "Noch keine öffentlichen Release-Artefakte freigegeben.",
    nodeEyebrow: "Monero Fast Node · MFN",
    nodeTitle: "Der schnelle Weg ins Monero-Netzwerk.",
    nodeBody: "Monero Fast Node ist die optimierte TEX8-Node-Infrastruktur. Sie liefert Blockchain-Daten effizient an die Wallet; dein nativer Wallet-Core prüft lokal, was dir gehört.",
    nodeSteps: [
      ["1", "Folgt der Monero-Blockchain", "MFN hält die Kette aktuell und beantwortet kompatible Wallet-Anfragen."],
      ["2", "Liefert den benötigten Bereich", "Der optimierte Stream und optionale ScanPacks reduzieren unnötige Wartezeit."],
      ["3", "Lässt die Wallet lokal prüfen", "Guthaben, Zahlungen und Sync-Status kommen weiterhin aus dem nativen Monero-Core."],
    ],
    nodeDownloadEyebrow: "Selbst betreiben",
    nodeDownloadTitle: "MFN installieren oder den Code prüfen.",
    nodeDownload: "Fertige Node-Pakete",
    nodeSource: "MFN-Quellcode",
    nodeReleaseGate: "Signierte MFN-Pakete werden nach der Plattformprüfung im Release-Bereich veröffentlicht.",
    openEyebrow: "Offen und überprüfbar",
    openTitle: "Open Source ist hier kein Etikett.",
    openBody: "App, MFN-Integration, Dienste, Tests, Benchmarks und bekannte Einschränkungen sind öffentlich einsehbar. Die verschiedenen Projektbereiche behalten ihre dokumentierten Open-Source-Lizenzen.",
    viewSource: "Repository öffnen",
    osiAlt: "Open Source Initiative Logo",
    osiNote: "Das OSI-Logo ist eine Marke der Open Source Initiative. Diese Website ist nicht mit OSI verbunden oder von OSI empfohlen.",
    faqEyebrow: "Kurz beantwortet",
    faqTitle: "Was Nutzer wirklich wissen wollen.",
    faqs: [
      ["Ist das eine echte Monero-Wallet?", "Ja. Der native Monero-Wallet-Core ist für Walletdaten, Transaktionen und Synchronisation maßgeblich."],
      ["Muss ich die Fast Wallet verwenden?", "Nein. Privacy funktioniert ohne gehostete Fast Wallet. Privacy + Komfort fügt sie als separate, optionale Empfangs-Wallet hinzu."],
      ["Kann TEX8 meine Coins ausgeben?", "Nein. Seed und Spend Key werden nicht an TEX8 übertragen. Der separate Fast-Wallet-Dienst kann keine Transaktion signieren."],
      ["Warum heißt der Node MFN?", "MFN steht für Monero Fast Node. Die optimierte TEX8-Node-Infrastruktur bleibt vollständig mit Monero kompatibel."],
      ["Sind Downloads schon öffentlich freigegeben?", "Noch nicht. Der Quellcode ist öffentlich; signierte Pakete erscheinen nach den jeweiligen Release- und Plattformprüfungen im GitHub-Releases-Bereich."],
    ],
    assistantTitle: "Monero Hilfe",
    assistantStatus: "Produktwissen aktiv",
    assistantOpen: "KI-Hilfe öffnen",
    assistantClose: "Assistent schließen",
    assistantWelcome: "Hallo! Frag mich zur Wallet, Fast Wallet, Ledger, Synchronisation oder zum Monero Fast Node.",
    assistantPlaceholder: "Frage zur Wallet …",
    assistantSend: "Senden",
    assistantSafety: "Keine Seeds, Keys, PINs oder Passwörter eingeben.",
    assistantError: "Der Assistent ist gerade nicht erreichbar. Bitte versuche es später erneut.",
    footer: "Developed with ❤️ by TEX8",
    statusChecking: "Dienste werden geprüft",
    statusOnline: "Dienste online",
    statusOffline: "Status derzeit nicht verfügbar",
  },
  en: {
    ...shared,
    lang: "en",
    switchLabel: "Deutsche Version",
    menu: "Open menu",
    close: "Close menu",
    download: "Download",
    nav: [["#wallet", "Wallet"], ["#features", "Features"], ["#enthusiast", "Monero Enthusiast"], ["#benchmarks", "Benchmark"], ["#mfn", "MFN"], ["#open-source", "Open source"]],
    heroSlides: [
      { eyebrow: "Monero for everyone", title: ["Private money.", "Finally simple."], body: "A clear Monero wallet for mobile and desktop. Your keys remain yours—from the first receive to the final confirmation.", primary: "Explore the apps", secondary: "How it works" },
      { eyebrow: "Mobile + desktop", title: ["One flow.", "Five platforms."], body: "React Native on iOS and Android, Tauri 2 on macOS, Windows, and Linux. Different hardware, the same simple experience.", primary: "Go to downloads", secondary: "See features" },
      { eyebrow: "Monero Fast Node", title: ["Sync faster.", "Monero stays Monero."], body: "Monero Fast Node accelerates the data path. Addresses, transactions, and consensus remain fully Monero compatible.", primary: "Understand MFN", secondary: "Review measurements" },
    ],
    heroCarouselLabel: "News and highlights",
    previousSlide: "Previous item",
    nextSlide: "Next item",
    slideLabel: "Item",
    trust: ["Self-custodial", "Open source", "Native Monero core"],
    preview: "Placeholder — real app screenshots will follow",
    simpleEyebrow: "Simple, not technical",
    simpleTitle: "Made for everyday life, not only experts.",
    simpleBody: "The app handles the complicated parts. You only see what you need for the next safe decision.",
    features: [
      ["Send in two steps", "Scan or paste an address, then choose an amount and review everything clearly."],
      ["Receive simply", "A large QR code, copyable address, subaddresses, and recent payments in one place."],
      ["Honest sync status", "Real phase, heights, and blocks remaining. Time appears only when the estimate is reliable."],
      ["One lock for the app", "Biometrics or OS protection opens every saved wallet together."],
      ["Ledger stays Ledger", "The spend key never leaves the device; signing still needs your Ledger approval."],
      ["Privacy or Privacy + convenience", "You choose whether a clearly marked Fast Wallet is created in addition."],
    ],
    modeEyebrow: "One clear choice",
    modeTitle: "Fast Wallet is an addition, not a replacement.",
    modeBody: "Your normal wallets remain local. Privacy + convenience adds a separate receive wallet for fast alerts.",
    privacy: "Privacy",
    privacyText: "Local Monero wallets without a hosted Fast Wallet.",
    comfort: "Privacy + convenience",
    comfortText: "The same private core plus a separate Fast Wallet for faster receive alerts.",
    modePoints: ["No seed or spend key is transferred.", "Fast Wallet is clearly labelled everywhere.", "You can change mode later in Settings.", "The open-source services can run on your own infrastructure."],
    enthusiastEyebrow: "Monero Enthusiast · optional community",
    enthusiastTitle: "Find people, ideas, and services—separate from your wallet.",
    enthusiastBody: "Monero Enthusiast is a separate community space inside the app. Your pseudonymous community identity is not linked to a wallet address, balance, history, seed, or keys.",
    enthusiastPoints: [
      ["Search locally", "A signed public catalog is downloaded to the device. Search and personal ranking run locally instead of becoming a server profile."],
      ["Connect by consent", "A personal connection is created only after the recipient accepts a profile-to-profile request."],
      ["Chat privately", "Accepted contacts can talk through a separate end-to-end encrypted Matrix conversation."],
      ["Stay in control", "Listings expire and can be deleted or reported. Community remains a separate, optional space."],
    ],
    enthusiastPreviewLabel: "Local community search",
    enthusiastPreviewPlaceholder: "Search for a node, meetup, or service …",
    enthusiastPreviewResults: [
      ["PERSON", "Panama Monero Meetup", "Community · approximate area optional"],
      ["IDEA", "Run your own Monero node", "Open source · beginner friendly"],
      ["SERVICE", "Understand Monero locally", "Public listing · 18 days"],
    ],
    enthusiastPrivacyLabel: "Wallet isolated",
    enthusiastPrivacyText: "No wallet address, balance, history, or keys are placed in the community profile.",
    enthusiastStatus: "Implemented in source · public release acceptance still pending",
    enthusiastDownload: "Download the app",
    enthusiastPrivacyLink: "Read the privacy model",
    benchmarkEyebrow: "Measured, not claimed",
    benchmarkTitle: "The same block range. A faster data path.",
    benchmarkBody: "All three current-core runs serially scanned the same 161,523 Mainnet blocks to the same frozen target height.",
    benchmarkRows: [
      ["Original Monero Wallet", "215 blocks/s · 12 min 31 s", "8%"],
      ["Monero Fast Wallet", "752 blocks/s · 3 min 35 s", "27%"],
      ["Fast Wallet + ScanPack", "2,802 blocks/s · 58 s", "100%"],
    ],
    faster: "faster in this test",
    benchmarkPending: "Validated current core · 13 August 2026",
    important: "Important",
    benchmarkNote: "One controlled comparison—not a speed promise for every device or network. The measured ScanPack server cache occupied 34.351 GiB.",
    method: "Method and raw evidence",
    derivationEyebrow: "Acceleration inside the wallet core",
    derivationTitle: "Cryptography uses the right hardware.",
    derivationBody: "The wallet core selects a verified CPU, Metal, or CUDA path for the device. Small jobs deliberately stay on the CPU; any accelerator error safely falls back to the CPU.",
    derivationUnit: "derivations per second",
    derivationRows: [
      { kind: "baseline", platform: "REFERENCE", status: "1 thread", title: "Original Monero Ref10", rate: "27,030.166", comparison: "1.00× · archived baseline" },
      { kind: "mobile", platform: "ARM64 MULTI-CORE", status: "NEON-capable", title: "Pixel 8 Pro · 9 workers", rate: "77,962.845", comparison: "7.83× against Ref10 on the same device" },
      { kind: "metal", platform: "APPLE METAL", status: "Product path", title: "Apple M4 · Metal M17", rate: "459,493.923", comparison: "17.00× normalized" },
      { kind: "cuda", platform: "NVIDIA CUDA", status: "Formal median", title: "RTX 5090 · CUDA C7", rate: "26,818,054.526", comparison: "992.15× normalized" },
    ],
    derivationNote: "Derivations/s measures D = 8 × a × R inside the cryptographic kernel—not blocks/s or complete synchronization time. Mobile currently uses the optimized ARM64 multi-worker path on NEON-capable hardware; no separate NEON kernel is claimed. CUDA is optional for compatible Windows/Linux packages; Metal is the verified macOS path.",
    derivationMethod: "Acceleration, method, and raw evidence",
    downloadEyebrow: "One wallet, every screen",
    downloadTitle: "Get the right package for your device.",
    downloadBody: "The platforms remain visible. Download links will be enabled only after public release.",
    coming: "Releases area",
    packages: { apk: "Download APK", dmg: "Download DMG", exe: "Download EXE", rpm: "Download RPM", deb: "Download DEB", appimage: "Download AppImage" },
    releaseGate: "No public release artifacts have been approved yet.",
    nodeEyebrow: "Monero Fast Node · MFN",
    nodeTitle: "The fast route into the Monero network.",
    nodeBody: "Monero Fast Node is the optimized TEX8 node infrastructure. It delivers blockchain data efficiently; your native wallet core checks locally what belongs to you.",
    nodeSteps: [["1", "Follows the Monero blockchain", "MFN keeps the chain current and answers compatible wallet requests."], ["2", "Delivers the required range", "Optimized streaming and optional ScanPacks reduce unnecessary waiting."], ["3", "Lets the wallet verify locally", "Balance, payments, and sync status still come from the native Monero core."]],
    nodeDownloadEyebrow: "Run it yourself",
    nodeDownloadTitle: "Install MFN or inspect the code.",
    nodeDownload: "Ready-built node packages",
    nodeSource: "MFN source code",
    nodeReleaseGate: "Signed MFN packages are published in the release area after platform acceptance.",
    openEyebrow: "Open and verifiable",
    openTitle: "Open source is more than a label here.",
    openBody: "App, MFN integration, services, tests, benchmarks, and known limitations are publicly reviewable. Each project area keeps its documented open-source license.",
    viewSource: "Open repository",
    osiAlt: "Open Source Initiative logo",
    osiNote: "The OSI logo trademark belongs to the Open Source Initiative. This site is not affiliated with or endorsed by OSI.",
    faqEyebrow: "Straight answers",
    faqTitle: "What users really want to know.",
    faqs: [["Is this a real Monero wallet?", "Yes. The native Monero wallet core is authoritative for wallet data, transactions, and synchronization."], ["Do I need Fast Wallet?", "No. Privacy works without a hosted Fast Wallet. Privacy + convenience adds it as a separate optional receive wallet."], ["Can TEX8 spend my coins?", "No. Seed and spend key are never transferred to TEX8. The separate Fast Wallet service cannot sign a transaction."], ["Why is the node called MFN?", "MFN stands for Monero Fast Node. The optimized TEX8 node infrastructure remains fully Monero compatible."], ["Are downloads publicly approved?", "Not yet. Source is public; signed packages will appear in GitHub Releases after their release and platform checks pass."]],
    assistantTitle: "Monero help",
    assistantStatus: "Product knowledge active",
    assistantOpen: "Open AI help",
    assistantClose: "Close assistant",
    assistantWelcome: "Hi! Ask me about the wallet, Fast Wallet, Ledger, synchronization, or Monero Fast Node.",
    assistantPlaceholder: "Ask about the wallet …",
    assistantSend: "Send",
    assistantSafety: "Never enter seeds, keys, PINs, or passwords.",
    assistantError: "The assistant is unavailable right now. Please try again later.",
    footer: "Developed with ❤️ by TEX8",
    statusChecking: "Checking services",
    statusOnline: "Services online",
    statusOffline: "Status currently unavailable",
  },
};

Object.assign(copy, generatedWebsiteCopy);
export { localeMetadata };
