#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../../.." && pwd)"

monero_source_dir="${MONERO_SOURCE_DIR:-${repo_root}/../monero-gui/monero}"
fast_crypto_dir="${FAST_CRYPTO_DIR:-${monero_source_dir}/external/monero-fast-crypto}"
output_dir="${OUTPUT_DIR:-${repo_root}/build/mobile-fast-crypto}"
android_api="${ANDROID_API:-24}"
targets_csv="${TARGETS:-android-arm64,android-armv7,android-x86,android-x86_64,ios-device,ios-sim-arm64,ios-sim-x86_64}"

if [[ ! -f "${fast_crypto_dir}/Cargo.toml" ]]; then
  echo "monero-fast-crypto Cargo.toml not found at ${fast_crypto_dir}" >&2
  exit 1
fi

# The wallet batch API depends on the authenticated Dalek extensions carried
# by third_party/curve25519-dalek-wallet-cpu. Without this Cargo override a
# mobile build would resolve the public 4.1.3 crate, which deliberately lacks
# those APIs.
source "${script_dir}/prepare-wallet-crypto-cpu-backend.sh"

find_android_ndk_home() {
  local candidates=()

  if [[ -n "${ANDROID_NDK_HOME:-}" ]]; then
    candidates+=("${ANDROID_NDK_HOME}")
  fi
  candidates+=("/opt/homebrew/share/android-commandlinetools/ndk/27.1.12297006")
  if [[ -n "${ANDROID_HOME:-}" ]]; then
    candidates+=("${ANDROID_HOME}/ndk/27.1.12297006")
  fi
  candidates+=("${HOME}/Library/Android/sdk/ndk/27.1.12297006")

  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -d "${candidate}/toolchains/llvm/prebuilt" ]]; then
      printf "%s" "${candidate}"
      return 0
    fi
  done

  return 1
}

manifest="${output_dir}/manifest.env"
mkdir -p "${output_dir}"
{
  echo "# Generated by native/monero-bridge/scripts/build-mobile-fast-crypto.sh"
  echo "MONERO_SOURCE_DIR=${monero_source_dir}"
  echo "FAST_CRYPTO_DIR=${fast_crypto_dir}"
  echo "OUTPUT_DIR=${output_dir}"
  echo "MONERO_WALLET_DALEK_CRATE_DIR=${MONERO_WALLET_DALEK_CRATE_DIR}"
  echo "MONERO_WALLET_DALEK_TREE=${MONERO_WALLET_DALEK_TREE}"
} > "${manifest}"

build_target() {
  local label="$1"
  local rust_target="$2"
  local linker="${3:-}"
  local ar="${4:-}"
  local manifest_key
  manifest_key="$(echo "${label}" | tr '[:lower:]-' '[:upper:]_')"

  echo "==> ${label}: ${rust_target}"
  rustup target add "${rust_target}" >/dev/null

  if [[ -n "${linker}" ]]; then
    if [[ ! -x "${linker}" ]]; then
      echo "linker not found or not executable: ${linker}" >&2
      exit 1
    fi
    local env_prefix
    env_prefix="$(echo "${rust_target}" | tr '[:lower:]-' '[:upper:]_')"
    export "CARGO_TARGET_${env_prefix}_LINKER=${linker}"
    if [[ -n "${ar}" ]]; then
      export "CARGO_TARGET_${env_prefix}_AR=${ar}"
    fi
  fi

  cargo --config "$(wallet_cpu_cargo_config)" build \
    --manifest-path "${fast_crypto_dir}/Cargo.toml" \
    --release \
    --locked \
    --target "${rust_target}"

  local source_lib="${fast_crypto_dir}/target/${rust_target}/release/libmonero_fast_crypto.a"
  local target_dir="${output_dir}/${label}"
  mkdir -p "${target_dir}"
  cp "${source_lib}" "${target_dir}/libmonero_fast_crypto.a"
  cp "${fast_crypto_dir}/include/monero_fast_crypto.h" "${target_dir}/monero_fast_crypto.h"

  {
    echo "${manifest_key}_RUST_TARGET=${rust_target}"
    echo "${manifest_key}_LIB=${target_dir}/libmonero_fast_crypto.a"
    echo "${manifest_key}_INCLUDE=${target_dir}/monero_fast_crypto.h"
  } >> "${manifest}"
}

IFS=',' read -r -a targets <<< "${targets_csv}"

target_requested() {
  local needle="$1"
  local target
  for target in "${targets[@]}"; do
    if [[ "${target}" == "${needle}" ]]; then
      return 0
    fi
  done
  return 1
}

android_target_requested() {
  local target
  for target in "${targets[@]}"; do
    case "${target}" in
      android-*) return 0 ;;
    esac
  done
  return 1
}

android_toolchain_bin=""
if android_target_requested; then
  android_ndk_home="${ANDROID_NDK_HOME:-}"
  if [[ -z "${android_ndk_home}" || ! -d "${android_ndk_home}/toolchains/llvm/prebuilt" ]]; then
    if ! android_ndk_home="$(find_android_ndk_home)"; then
      echo "Android NDK not found. Set ANDROID_NDK_HOME to an installed NDK." >&2
      exit 1
    fi
  fi

  android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-aarch64/bin"
  if [[ ! -d "${android_toolchain_bin}" ]]; then
    android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-x86_64/bin"
  fi
fi

for target in "${targets[@]}"; do
  case "${target}" in
    android-arm64)
      build_target \
        android-arm64 \
        aarch64-linux-android \
        "${android_toolchain_bin}/aarch64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-armv7)
      build_target \
        android-armv7 \
        armv7-linux-androideabi \
        "${android_toolchain_bin}/armv7a-linux-androideabi${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86)
      build_target \
        android-x86 \
        i686-linux-android \
        "${android_toolchain_bin}/i686-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86_64)
      build_target \
        android-x86_64 \
        x86_64-linux-android \
        "${android_toolchain_bin}/x86_64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    ios-device)
      build_target ios-device aarch64-apple-ios
      ;;
    ios-sim-arm64)
      build_target ios-sim-arm64 aarch64-apple-ios-sim
      ;;
    ios-sim-x86_64)
      build_target ios-sim-x86_64 x86_64-apple-ios
      ;;
    *)
      echo "unknown TARGETS entry: ${target}" >&2
      exit 1
      ;;
  esac
done

ios_device_lib="${output_dir}/ios-device/libmonero_fast_crypto.a"
ios_sim_arm64_lib="${output_dir}/ios-sim-arm64/libmonero_fast_crypto.a"
ios_sim_x86_64_lib="${output_dir}/ios-sim-x86_64/libmonero_fast_crypto.a"
ios_sim_universal_dir="${output_dir}/ios-simulator-universal"
xcframework_path="${output_dir}/monero_fast_crypto.xcframework"

if target_requested ios-device &&
   target_requested ios-sim-arm64 &&
   target_requested ios-sim-x86_64 &&
   [[ -f "${ios_device_lib}" &&
      -f "${ios_sim_arm64_lib}" &&
      -f "${ios_sim_x86_64_lib}" ]] &&
   command -v lipo >/dev/null &&
   command -v xcodebuild >/dev/null; then
  echo "==> ios-xcframework"
  mkdir -p "${ios_sim_universal_dir}"
  lipo -create \
    "${ios_sim_arm64_lib}" \
    "${ios_sim_x86_64_lib}" \
    -output "${ios_sim_universal_dir}/libmonero_fast_crypto.a"
  cp "${fast_crypto_dir}/include/monero_fast_crypto.h" \
    "${ios_sim_universal_dir}/monero_fast_crypto.h"

  ios_device_headers="${output_dir}/headers/ios-device"
  ios_sim_headers="${output_dir}/headers/ios-simulator"
  rm -rf "${ios_device_headers}" "${ios_sim_headers}"
  mkdir -p "${ios_device_headers}" "${ios_sim_headers}"
  cp "${fast_crypto_dir}/include/monero_fast_crypto.h" \
    "${ios_device_headers}/monero_fast_crypto.h"
  cp "${fast_crypto_dir}/include/monero_fast_crypto.h" \
    "${ios_sim_headers}/monero_fast_crypto.h"

  rm -rf "${xcframework_path}"
  xcodebuild -create-xcframework \
    -library "${ios_device_lib}" \
    -headers "${ios_device_headers}" \
    -library "${ios_sim_universal_dir}/libmonero_fast_crypto.a" \
    -headers "${ios_sim_headers}" \
    -output "${xcframework_path}" >/dev/null

  {
    echo "IOS_SIMULATOR_UNIVERSAL_LIB=${ios_sim_universal_dir}/libmonero_fast_crypto.a"
    echo "IOS_SIMULATOR_UNIVERSAL_INCLUDE=${ios_sim_universal_dir}/monero_fast_crypto.h"
    echo "IOS_XCFRAMEWORK=${xcframework_path}"
  } >> "${manifest}"
fi

echo "Built mobile monero-fast-crypto artifacts under ${output_dir}"
echo "Manifest: ${manifest}"
