// Generated by scripts/generate-product-locales.mjs. Do not edit by hand.
export type GeneratedRuntimeCatalog = Record<string, string>;
export const generatedRuntimeCatalogLoaders = {
  "es": () => import("./lazy/es.generated").then(({ default: createCatalog }) => createCatalog()),
  "pt-BR": () => import("./lazy/pt-BR.generated").then(({ default: createCatalog }) => createCatalog()),
  "ru": () => import("./lazy/ru.generated").then(({ default: createCatalog }) => createCatalog()),
  "vi": () => import("./lazy/vi.generated").then(({ default: createCatalog }) => createCatalog()),
  "id": () => import("./lazy/id.generated").then(({ default: createCatalog }) => createCatalog()),
  "uk": () => import("./lazy/uk.generated").then(({ default: createCatalog }) => createCatalog()),
  "tr": () => import("./lazy/tr.generated").then(({ default: createCatalog }) => createCatalog()),
  "hi": () => import("./lazy/hi.generated").then(({ default: createCatalog }) => createCatalog()),
  "ur": () => import("./lazy/ur.generated").then(({ default: createCatalog }) => createCatalog()),
  "fr": () => import("./lazy/fr.generated").then(({ default: createCatalog }) => createCatalog()),
  "fil": () => import("./lazy/fil.generated").then(({ default: createCatalog }) => createCatalog()),
  "ja": () => import("./lazy/ja.generated").then(({ default: createCatalog }) => createCatalog()),
  "ko": () => import("./lazy/ko.generated").then(({ default: createCatalog }) => createCatalog()),
  "ar": () => import("./lazy/ar.generated").then(({ default: createCatalog }) => createCatalog()),
  "zh-CN": () => import("./lazy/zh-CN.generated").then(({ default: createCatalog }) => createCatalog()),
  "zh-TW": () => import("./lazy/zh-TW.generated").then(({ default: createCatalog }) => createCatalog()),
} as const;
