export type DiagnosticCopy = (
  key: string,
  params?: Record<string, string | number>,
) => string;

const exactKeys: Readonly<Record<string, string>> = {
  Core: 'diagnostic.category.core',
  Security: 'diagnostic.category.security',
  Network: 'diagnostic.category.network',
  Performance: 'diagnostic.category.performance',
  Wallet: 'diagnostic.category.wallet',
  'Fast Wallet': 'diagnostic.category.fastWallet',
  Hardware: 'diagnostic.category.hardware',
  'Native Monero Core': 'diagnostic.test.nativeCore',
  'Protected storage round-trip': 'diagnostic.test.secureStorage',
  'Node configuration': 'diagnostic.test.nodeConfiguration',
  'Shared blockchain connection': 'diagnostic.test.sharedConnection',
  'gRPC / ScanPack path': 'diagnostic.test.scanPack',
  'Block download throughput': 'diagnostic.test.throughput',
  'Wallet snapshot': 'diagnostic.test.walletSnapshot',
  'Multi-wallet fan-out': 'diagnostic.test.multiWallet',
  'Fast Wallet local integrity': 'diagnostic.test.fastWalletIntegrity',
  'Encrypted Fast Wallet hosting': 'diagnostic.test.fastWalletHosting',
  'Key derivation engine': 'diagnostic.test.derivationEngine',
  'Ledger transport': 'diagnostic.test.ledgerTransport',
  Backend: 'diagnostic.metric.backend',
  'Product Core ABI': 'diagnostic.metric.productCoreAbi',
  'Product Core schema': 'diagnostic.metric.productCoreSchema',
  Schema: 'diagnostic.metric.schema',
  'Diagnostic registry': 'diagnostic.metric.registry',
  'AppVault state schema': 'diagnostic.metric.appVaultSchema',
  Mode: 'diagnostic.metric.mode',
  State: 'diagnostic.metric.state',
  Phase: 'diagnostic.metric.phase',
  'Chain height': 'diagnostic.metric.chainHeight',
  'Target height': 'diagnostic.metric.targetHeight',
  'Transport starts': 'diagnostic.metric.transportStarts',
  'Provider generation': 'diagnostic.metric.providerGeneration',
  Batches: 'diagnostic.metric.batches',
  Blocks: 'diagnostic.metric.blocks',
  Decoded: 'diagnostic.metric.decoded',
  'Network throughput': 'diagnostic.metric.networkThroughput',
  'Payload throughput': 'diagnostic.metric.payloadThroughput',
  'Block throughput': 'diagnostic.metric.blockThroughput',
  'Network sample': 'diagnostic.metric.networkSample',
  'Payload sample': 'diagnostic.metric.payloadSample',
  'Fetch time': 'diagnostic.metric.fetchTime',
  'Wallet height': 'diagnostic.metric.walletHeight',
  'Daemon height': 'diagnostic.metric.daemonHeight',
  Synchronized: 'diagnostic.metric.synchronized',
  'Registered wallets': 'diagnostic.metric.registeredWallets',
  'Joined wallets': 'diagnostic.metric.joinedWallets',
  'Scan workers': 'diagnostic.metric.scanWorkers',
  'Stalled wallets': 'diagnostic.metric.stalledWallets',
  Deliveries: 'diagnostic.metric.deliveries',
  'Fast Wallets': 'diagnostic.metric.fastWallets',
  Hosted: 'diagnostic.metric.hosted',
  'Missing credentials': 'diagnostic.metric.missingCredentials',
  'Missing registrations': 'diagnostic.metric.missingRegistrations',
  'Invalid assignments': 'diagnostic.metric.invalidAssignments',
  'Official Worker': 'diagnostic.metric.officialWorker',
  'Private Worker': 'diagnostic.metric.privateWorker',
  Invalid: 'diagnostic.metric.invalid',
  'Hosted assignments': 'diagnostic.metric.hostedAssignments',
  'Verified Workers': 'diagnostic.metric.verifiedWorkers',
  'CPU workers': 'diagnostic.metric.cpuWorkers',
  Transport: 'diagnostic.metric.transport',
  Devices: 'diagnostic.metric.devices',
  configured: 'diagnostic.value.configured',
  disabled: 'diagnostic.value.disabled',
  yes: 'diagnostic.value.yes',
  no: 'diagnostic.value.no',
  none: 'diagnostic.value.none',
  unknown: 'diagnostic.value.unknown',
  'The packaged Monero wallet core is linked and callable.': 'diagnostic.summary.coreReady',
  'The native Monero wallet core is missing.': 'diagnostic.summary.coreMissing',
  'A temporary AppVault credential was stored, read and deleted.': 'diagnostic.summary.secureStorageReady',
  'A temporary credential was stored and read back successfully.': 'diagnostic.summary.secureStorageReady',
  'AppVault returned a different diagnostic value.': 'diagnostic.summary.secureStorageFailed',
  'Protected storage did not return the temporary credential.': 'diagnostic.summary.secureStorageFailed',
  'Monero Fast Node gRPC and daemon endpoints are configured.': 'diagnostic.summary.nodeOptimized',
  'Original Monero RPC is configured.': 'diagnostic.summary.nodeOriginal',
  'The active node profile is incomplete.': 'diagnostic.summary.nodeIncomplete',
  'Open at least one wallet to exercise the shared node connection.': 'diagnostic.summary.openWalletForNetwork',
  'One process-wide connection supplies every open wallet.': 'diagnostic.summary.sharedReady',
  'The first shared node handshake is still pending.': 'diagnostic.summary.sharedPending',
  'The shared connection has not completed its first handshake yet.': 'diagnostic.summary.sharedPending',
  'The active profile deliberately uses original Monero RPC.': 'diagnostic.summary.originalPath',
  'gRPC is configured, but no authenticated block batch has arrived yet.': 'diagnostic.summary.scanPackPending',
  'The optimized transport returned decoded shared block batches.': 'diagnostic.summary.scanPackReady',
  'No non-empty block batch has been downloaded in this app session yet.': 'diagnostic.summary.noThroughput',
  'Measured directly at the Monero node transport.': 'diagnostic.summary.throughputReady',
  'Measured, but the last batch is too small for a stable capacity estimate.': 'diagnostic.summary.throughputSmall',
  'Measured, but the most recent batch is too small for a stable capacity estimate.': 'diagnostic.summary.throughputSmall',
  'Open a wallet to test its local Core snapshot.': 'diagnostic.summary.openWalletForSnapshot',
  'Open a wallet to test its local balance and height snapshot.': 'diagnostic.summary.openWalletForSnapshot',
  'The active wallet returned a consistent local Core snapshot.': 'diagnostic.summary.snapshotReady',
  'The wallet height is inconsistent with the authenticated chain target.': 'diagnostic.summary.snapshotInvalid',
  'No wallet is currently joined to the shared sync coordinator.': 'diagnostic.summary.noJoinedWallet',
  'At least one wallet scanner is stalled.': 'diagnostic.summary.walletStalled',
  'Downloaded batches are fanned out to all joined wallet scanners.': 'diagnostic.summary.fanoutReady',
  'Downloaded batches are fanned out to the joined wallet scanners.': 'diagnostic.summary.fanoutReady',
  'No Fast Wallet is configured.': 'diagnostic.summary.noFastWallet',
  'Every Fast Wallet has protected local credentials and consistent assignment state.': 'diagnostic.summary.fastWalletReady',
  'Every Fast Wallet has an independent registry entry and protected credential.': 'diagnostic.summary.fastWalletReady',
  'Fast Wallet credentials or assignment state are incomplete.': 'diagnostic.summary.fastWalletInvalid',
  'Fast Wallet registry or protected credential data is incomplete.': 'diagnostic.summary.fastWalletInvalid',
  'No Fast Wallet currently has hosted encrypted scan data.': 'diagnostic.summary.noHostedFastWallet',
  'Every pinned Worker descriptor and protected assignment was verified without changing it.': 'diagnostic.summary.hostingReady',
  'Assignment metadata is complete; the official Worker descriptor was signature-checked when applicable.': 'diagnostic.summary.hostingReady',
  'At least one encrypted assignment is incomplete or expired.': 'diagnostic.summary.hostingInvalid',
  'The packaged engine passed the bounded public-vector benchmark.': 'diagnostic.summary.engineReady',
  'The CPU derivation backend did not return a verified result.': 'diagnostic.summary.engineInvalid',
  'Ledger is not supported on this platform.': 'diagnostic.summary.ledgerUnsupported',
  'No Ledger is connected; no permission dialog was opened.': 'diagnostic.summary.ledgerMissing',
  'No Ledger is connected; no permission prompt was opened.': 'diagnostic.summary.ledgerMissing',
  'The Ledger transport is available.': 'diagnostic.summary.ledgerReady',
  'Ledger is visible, but transport permission is required.': 'diagnostic.summary.ledgerPermission',
};

export function localizeDiagnosticText(value: string, copy: DiagnosticCopy): string {
  const key = exactKeys[value];
  if (key) return copy(key);
  const sharedState = /^The shared connection is (.+)\.$/.exec(value);
  if (sharedState) return copy('diagnostic.summary.sharedState', { state: sharedState[1] });
  return value;
}
