#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
output_dir="${OUTPUT_DIR:-${repo_root}/build/mobile-community-matrix}"
target_cache="${CARGO_TARGET_DIR:-${repo_root}/build/community-matrix-target}"
android_api="${ANDROID_API:-24}"
targets_csv="${TARGETS:-android-arm64,ios-sim-arm64}"
with_community_runtime="${WITH_COMMUNITY_RUNTIME:-0}"
harrier_library_root="${TEX8_COMMUNITY_HARRIER_LIBRARY_ROOT:-}"

if [[ "${with_community_runtime}" != "0" && "${with_community_runtime}" != "1" ]]; then
  echo "WITH_COMMUNITY_RUNTIME must be 0 or 1" >&2
  exit 1
fi
if [[ "${with_community_runtime}" == "1" && -z "${harrier_library_root}" ]]; then
  echo "TEX8_COMMUNITY_HARRIER_LIBRARY_ROOT is required for the complete Community runtime" >&2
  exit 1
fi

find_android_ndk_home() {
  local candidates=()
  if [[ -n "${ANDROID_NDK_HOME:-}" ]]; then
    candidates+=("${ANDROID_NDK_HOME}")
  fi
  if [[ -n "${ANDROID_HOME:-}" ]]; then
    candidates+=("${ANDROID_HOME}/ndk/27.1.12297006")
  fi
  candidates+=(
    "${HOME}/Library/Android/sdk/ndk/27.1.12297006"
    "/opt/homebrew/share/android-commandlinetools/ndk/27.1.12297006"
  )
  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -d "${candidate}/toolchains/llvm/prebuilt" ]]; then
      printf "%s" "${candidate}"
      return 0
    fi
  done
  return 1
}

mkdir -p "${output_dir}"
manifest="${output_dir}/manifest.env"
{
  echo "# Generated by native/community-matrix-core/build-mobile.sh"
  echo "SOURCE_DIR=${script_dir}"
  echo "OUTPUT_DIR=${output_dir}"
  echo "MATRIX_SDK_VERSION=0.18.0"
  echo "WITH_COMMUNITY_RUNTIME=${with_community_runtime}"
} > "${manifest}"

build_target() {
  local label="$1"
  local rust_target="$2"
  local linker="${3:-}"
  local ar="${4:-}"
  local target_env
  target_env="$(echo "${rust_target}" | tr '[:lower:]-' '[:upper:]_')"

  echo "==> Community Matrix ${label}: ${rust_target}"
  rustup target add "${rust_target}" >/dev/null
  if [[ -n "${linker}" ]]; then
    [[ -x "${linker}" ]] || {
      echo "linker not found or not executable: ${linker}" >&2
      exit 1
    }
    export "CARGO_TARGET_${target_env}_LINKER=${linker}"
    export "CC_${rust_target//-/_}=${linker}"
    # Matrix's FFI graph includes link-cplusplus; setting only the C linker
    # lets its build script search PATH for a non-existent Android C++ driver.
    local cxx_linker="${linker%clang}clang++"
    export "CXX_${rust_target//-/_}=${cxx_linker}"
    if [[ -n "${ar}" ]]; then
      export "CARGO_TARGET_${target_env}_AR=${ar}"
      export "AR_${rust_target//-/_}=${ar}"
    fi
  fi

  local feature_args=()
  if [[ "${with_community_runtime}" == "1" ]]; then
    feature_args=(--features community-runtime)
  fi
  CARGO_TARGET_DIR="${target_cache}" cargo build \
    --manifest-path "${script_dir}/Cargo.toml" \
    --release \
    --locked \
    --target "${rust_target}" \
    "${feature_args[@]}"

  local destination="${output_dir}/${label}"
  mkdir -p "${destination}"
  cp "${target_cache}/${rust_target}/release/libcommunity_matrix_core.a" \
    "${destination}/libcommunity_matrix_core.a"
  cp "${script_dir}/include/community_matrix_core.h" \
    "${destination}/community_matrix_core.h"
  if [[ "${with_community_runtime}" == "1" ]]; then
    local harrier_library_suffix="${HARRIER_LIBRARY_SUFFIX:-.a}"
    local harrier_library="${harrier_library_root}/${label}/libtex8_community_harrier_runtime${harrier_library_suffix}"
    [[ -f "${harrier_library}" ]] || {
      echo "verified Harrier runtime not found: ${harrier_library}" >&2
      exit 1
    }
    cp "${harrier_library}" \
      "${destination}/libtex8_community_harrier_runtime${harrier_library_suffix}"
    cp "${repo_root}/native/community-runtime-core/include/community_runtime_core.h" \
      "${destination}/community_runtime_core.h"
  fi
  {
    echo "$(echo "${label}" | tr '[:lower:]-' '[:upper:]_')_RUST_TARGET=${rust_target}"
    echo "$(echo "${label}" | tr '[:lower:]-' '[:upper:]_')_LIB=${destination}/libcommunity_matrix_core.a"
    if [[ "${with_community_runtime}" == "1" ]]; then
      echo "$(echo "${label}" | tr '[:lower:]-' '[:upper:]_')_HARRIER_LIB=${destination}/libtex8_community_harrier_runtime${harrier_library_suffix}"
    fi
  } >> "${manifest}"
}

IFS=',' read -r -a targets <<< "${targets_csv}"
android_toolchain_bin=""
for target in "${targets[@]}"; do
  if [[ "${target}" == android-* && -z "${android_toolchain_bin}" ]]; then
    if ! android_ndk_home="$(find_android_ndk_home)"; then
      echo "Android NDK not found. Set ANDROID_NDK_HOME." >&2
      exit 1
    fi
    android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-aarch64/bin"
    if [[ ! -d "${android_toolchain_bin}" ]]; then
      android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-x86_64/bin"
    fi
  fi
done

for target in "${targets[@]}"; do
  case "${target}" in
    android-arm64)
      build_target "${target}" aarch64-linux-android \
        "${android_toolchain_bin}/aarch64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-armv7)
      build_target "${target}" armv7-linux-androideabi \
        "${android_toolchain_bin}/armv7a-linux-androideabi${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86)
      build_target "${target}" i686-linux-android \
        "${android_toolchain_bin}/i686-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86_64)
      build_target "${target}" x86_64-linux-android \
        "${android_toolchain_bin}/x86_64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    ios-device)
      build_target "${target}" aarch64-apple-ios
      ;;
    ios-sim-arm64)
      build_target "${target}" aarch64-apple-ios-sim
      ;;
    ios-sim-x86_64)
      build_target "${target}" x86_64-apple-ios
      ;;
    *)
      echo "unknown TARGETS entry: ${target}" >&2
      exit 1
      ;;
  esac
done

echo "Built Community Matrix mobile artifacts under ${output_dir}"
echo "Manifest: ${manifest}"
