#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"
output_dir="${OUTPUT_DIR:-${repo_root}/build/mobile-fast-wallet-protocol}"
android_api="${ANDROID_API:-24}"
targets_csv="${TARGETS:-android-arm64,android-armv7,android-x86,android-x86_64,ios-device,ios-sim-arm64,ios-sim-x86_64}"
source "${repo_root}/native/monero-bridge/scripts/prepare-common-monero-core.sh"
monero_source_dir="${MONERO_SOURCE_DIR}"
monero_fast_crypto_source="${monero_source_dir}/external/monero-fast-crypto/src/lib.rs"

if [[ ! -f "${monero_fast_crypto_source}" ]]; then
  echo "Authenticated Monero acceleration source is missing: ${monero_fast_crypto_source}" >&2
  echo "Set MONERO_SOURCE_DIR to the prepared TEX8 Monero source tree." >&2
  exit 1
fi

# Both mobile C ABIs are compiled into one archive. Otherwise Android/iOS
# receive two copies of Rust's standard library and the final native link is
# either rejected or depends on unsafe duplicate-symbol behavior.
source "${repo_root}/native/monero-bridge/scripts/prepare-wallet-crypto-cpu-backend.sh"
export MONERO_FAST_CRYPTO_SOURCE="${monero_fast_crypto_source}"

# Cargo records path-patched dependencies differently in Cargo.lock. Reconcile
# that source-only change in an isolated build copy so the checked-in lock
# remains valid for ordinary protocol/service builds against crates.io.
mobile_build_root="$(mktemp -d "${TMPDIR:-/tmp}/tex8-fast-wallet-protocol.XXXXXX")"
mobile_build_source="${mobile_build_root}/fast-wallet-protocol"
mkdir -p "${mobile_build_source}"
trap 'rm -rf "${mobile_build_root}"' EXIT
cp "${script_dir}/Cargo.toml" "${script_dir}/Cargo.lock" "${mobile_build_source}/"
cp -R "${script_dir}/src" "${script_dir}/include" "${script_dir}/test-vectors" \
  "${mobile_build_source}/"
# Preserve the repository-relative dependency layout inside the isolated
# build, but copy source inputs only. Copying the dependency's reproducible
# `target/` cache can add gigabytes and makes a clean mobile build depend on
# stale host artifacts.
mkdir -p "${mobile_build_root}/mfw-recipient-protocol"
cp \
  "${repo_root}/native/mfw-recipient-protocol/Cargo.toml" \
  "${repo_root}/native/mfw-recipient-protocol/Cargo.lock" \
  "${repo_root}/native/mfw-recipient-protocol/README.md" \
  "${mobile_build_root}/mfw-recipient-protocol/"
cp -R "${repo_root}/native/mfw-recipient-protocol/src" \
  "${mobile_build_root}/mfw-recipient-protocol/"
cargo --config "$(wallet_cpu_cargo_config)" metadata \
  --manifest-path "${mobile_build_source}/Cargo.toml" \
  --features mobile-fast-crypto \
  --format-version 1 >/dev/null

find_android_ndk_home() {
  local candidates=()
  if [[ -n "${ANDROID_NDK_HOME:-}" ]]; then
    candidates+=("${ANDROID_NDK_HOME}")
  fi
  if [[ -n "${ANDROID_HOME:-}" ]]; then
    candidates+=("${ANDROID_HOME}/ndk/27.1.12297006")
  fi
  candidates+=(
    "${HOME}/Library/Android/sdk/ndk/27.1.12297006"
    "/opt/homebrew/share/android-commandlinetools/ndk/27.1.12297006"
  )
  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -d "${candidate}/toolchains/llvm/prebuilt" ]]; then
      printf "%s" "${candidate}"
      return 0
    fi
  done
  return 1
}

mkdir -p "${output_dir}"
manifest="${output_dir}/manifest.env"
{
  echo "# Generated by native/fast-wallet-protocol/build-mobile.sh"
  echo "PROTOCOL_SOURCE_DIR=${script_dir}"
  echo "MONERO_FAST_CRYPTO_SOURCE=${monero_fast_crypto_source}"
  echo "MONERO_COMMON_CORE_TREE=${MONERO_COMMON_CORE_TREE}"
  echo "MONERO_WALLET_DALEK_TREE=${MONERO_WALLET_DALEK_TREE}"
  echo "OUTPUT_DIR=${output_dir}"
} > "${manifest}"

build_target() {
  local label="$1"
  local rust_target="$2"
  local linker="${3:-}"
  local ar="${4:-}"
  local env_prefix
  env_prefix="$(echo "${rust_target}" | tr '[:lower:]-' '[:upper:]_')"

  echo "==> Fast Wallet protocol ${label}: ${rust_target}"
  rustup target add "${rust_target}" >/dev/null
  if [[ -n "${linker}" ]]; then
    [[ -x "${linker}" ]] || {
      echo "linker not found or not executable: ${linker}" >&2
      exit 1
    }
    export "CARGO_TARGET_${env_prefix}_LINKER=${linker}"
    if [[ -n "${ar}" ]]; then
      export "CARGO_TARGET_${env_prefix}_AR=${ar}"
    fi
  fi

  cargo --config "$(wallet_cpu_cargo_config)" build \
    --manifest-path "${mobile_build_source}/Cargo.toml" \
    --features mobile-fast-crypto \
    --release \
    --locked \
    --target "${rust_target}"

  local target_dir="${output_dir}/${label}"
  mkdir -p "${target_dir}"
  cp "${mobile_build_source}/target/${rust_target}/release/libfast_wallet_protocol.a" \
    "${target_dir}/libfast_wallet_protocol.a"
  cp "${script_dir}/include/fast_wallet_protocol.h" \
    "${target_dir}/fast_wallet_protocol.h"
  cp "${monero_source_dir}/external/monero-fast-crypto/include/monero_fast_crypto.h" \
    "${target_dir}/monero_fast_crypto.h"
  {
    echo "$(echo "${label}" | tr '[:lower:]-' '[:upper:]_')_RUST_TARGET=${rust_target}"
    echo "$(echo "${label}" | tr '[:lower:]-' '[:upper:]_')_LIB=${target_dir}/libfast_wallet_protocol.a"
  } >> "${manifest}"
}

IFS=',' read -r -a targets <<< "${targets_csv}"
android_requested=0
for target in "${targets[@]}"; do
  case "${target}" in
    android-*) android_requested=1 ;;
  esac
done

android_toolchain_bin=""
if [[ "${android_requested}" == "1" ]]; then
  if ! android_ndk_home="$(find_android_ndk_home)"; then
    echo "Android NDK not found. Set ANDROID_NDK_HOME." >&2
    exit 1
  fi
  android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-aarch64/bin"
  if [[ ! -d "${android_toolchain_bin}" ]]; then
    android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-x86_64/bin"
  fi
fi

for target in "${targets[@]}"; do
  case "${target}" in
    android-arm64)
      build_target "${target}" aarch64-linux-android \
        "${android_toolchain_bin}/aarch64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-armv7)
      build_target "${target}" armv7-linux-androideabi \
        "${android_toolchain_bin}/armv7a-linux-androideabi${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86)
      build_target "${target}" i686-linux-android \
        "${android_toolchain_bin}/i686-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86_64)
      build_target "${target}" x86_64-linux-android \
        "${android_toolchain_bin}/x86_64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    ios-device)
      build_target "${target}" aarch64-apple-ios
      ;;
    ios-sim-arm64)
      build_target "${target}" aarch64-apple-ios-sim
      ;;
    ios-sim-x86_64)
      build_target "${target}" x86_64-apple-ios
      ;;
    *)
      echo "unknown TARGETS entry: ${target}" >&2
      exit 1
      ;;
  esac
done

echo "Built Fast Wallet protocol mobile artifacts under ${output_dir}"
echo "Manifest: ${manifest}"
