#!/usr/bin/env bash
set -euo pipefail

# Build the shared Product Core ABI as one target-native static archive. The
# archive is used by the product CLI CMake graph during mobile wallet_api
# configuration even though wallet_api itself does not call the CLI ABI.

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output_dir="${OUTPUT_DIR:-${script_dir}/target/mobile}"
android_api="${ANDROID_API:-24}"
targets_csv="${TARGETS:-android-arm64,android-armv7,android-x86,android-x86_64,ios-device,ios-sim-arm64,ios-sim-x86_64}"
target_dir="${MFW_PRODUCT_CORE_MOBILE_TARGET_DIR:-${output_dir}/cargo-target}"

find_android_ndk_home() {
  local candidates=()
  [[ -z "${ANDROID_NDK_HOME:-}" ]] || candidates+=("${ANDROID_NDK_HOME}")
  [[ -z "${ANDROID_HOME:-}" ]] || candidates+=("${ANDROID_HOME}/ndk/27.1.12297006")
  candidates+=(
    "${HOME}/Library/Android/sdk/ndk/27.1.12297006"
    "/opt/homebrew/share/android-commandlinetools/ndk/27.1.12297006"
  )
  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -d "${candidate}/toolchains/llvm/prebuilt" ]]; then
      printf '%s' "${candidate}"
      return 0
    fi
  done
  return 1
}

build_target() {
  local label="$1"
  local rust_target="$2"
  local linker="${3:-}"
  local ar="${4:-}"
  local env_prefix
  env_prefix="$(printf '%s' "${rust_target}" | tr '[:lower:]-' '[:upper:]_')"

  rustup target add "${rust_target}" >/dev/null
  if [[ -n "${linker}" ]]; then
    [[ -x "${linker}" ]] || {
      echo "Product Core linker is unavailable: ${linker}" >&2
      exit 1
    }
    export "CARGO_TARGET_${env_prefix}_LINKER=${linker}"
    [[ -z "${ar}" ]] || export "CARGO_TARGET_${env_prefix}_AR=${ar}"
  fi

  echo "==> Product Core ${label}: ${rust_target}"
  CARGO_TARGET_DIR="${target_dir}" cargo build \
    --manifest-path "${script_dir}/Cargo.toml" \
    --release \
    --locked \
    --target "${rust_target}"

  local source_library="${target_dir}/${rust_target}/release/libmfw_product_core.a"
  local target_output="${output_dir}/${label}"
  [[ -f "${source_library}" ]] || {
    echo "Product Core static archive was not produced: ${source_library}" >&2
    exit 1
  }
  mkdir -p "${target_output}"
  cp "${source_library}" "${target_output}/libmfw_product_core.a"
}

IFS=',' read -r -a targets <<< "${targets_csv}"
android_toolchain_bin=""
for target in "${targets[@]}"; do
  case "${target}" in
    android-*)
      if [[ -z "${android_toolchain_bin}" ]]; then
        android_ndk_home="$(find_android_ndk_home)" || {
          echo "Android NDK not found. Set ANDROID_NDK_HOME." >&2
          exit 1
        }
        android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-aarch64/bin"
        [[ -d "${android_toolchain_bin}" ]] || \
          android_toolchain_bin="${android_ndk_home}/toolchains/llvm/prebuilt/darwin-x86_64/bin"
      fi
      ;;
  esac
done

mkdir -p "${output_dir}"
manifest="${output_dir}/manifest.env"

for target in "${targets[@]}"; do
  case "${target}" in
    android-arm64)
      build_target "${target}" aarch64-linux-android \
        "${android_toolchain_bin}/aarch64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-armv7)
      build_target "${target}" armv7-linux-androideabi \
        "${android_toolchain_bin}/armv7a-linux-androideabi${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86)
      build_target "${target}" i686-linux-android \
        "${android_toolchain_bin}/i686-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    android-x86_64)
      build_target "${target}" x86_64-linux-android \
        "${android_toolchain_bin}/x86_64-linux-android${android_api}-clang" \
        "${android_toolchain_bin}/llvm-ar"
      ;;
    ios-device) build_target "${target}" aarch64-apple-ios ;;
    ios-sim-arm64) build_target "${target}" aarch64-apple-ios-sim ;;
    ios-sim-x86_64) build_target "${target}" x86_64-apple-ios ;;
    *)
      echo "Unknown Product Core mobile target: ${target}" >&2
      exit 1
      ;;
  esac
done

# Each platform build invokes this script with only its own target. Rebuild the
# manifest from every authenticated archive already present in the same output
# root so a later iOS build cannot erase the Android identity (or vice versa).
{
  echo "# Generated by native/product-core/build-mobile.sh"
  echo "PRODUCT_CORE_SOURCE_DIR=${script_dir}"
  echo "OUTPUT_DIR=${output_dir}"
  for label in \
    android-arm64 android-armv7 android-x86 android-x86_64 \
    ios-device ios-sim-arm64 ios-sim-x86_64; do
    library="${output_dir}/${label}/libmfw_product_core.a"
    if [[ -f "${library}" ]]; then
      key="$(printf '%s' "${label}" | tr '[:lower:]-' '[:upper:]_')"
      echo "${key}_LIB=${library}"
    fi
  done
} > "${manifest}"

echo "Built Product Core mobile artifacts under ${output_dir}"
echo "Manifest: ${manifest}"
